name: Validate Branch Flow

on:
  pull_request:
    branches:
      - uat
      - prod

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch promotion rules
        run: |
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

          # Rule 1: Only poc → uat allowed
          if [[ "${{ github.base_ref }}" == "uat" && "${{ github.head_ref }}" != "poc" ]]; then
            echo "❌ ERROR: Only 'poc' can merge into 'uat'."
            exit 1
          fi

          # Rule 2: Only uat → production allowed
          if [[ "${{ github.base_ref }}" == "prod" && "${{ github.head_ref }}" != "uat" ]]; then
            echo "❌ ERROR: Only 'uat' can merge into 'production'."
            exit 1
          fi

          # Explicit block: poc → production (never allowed)
          if [[ "${{ github.base_ref }}" == "production" && "${{ github.head_ref }}" == "poc" ]]; then
            echo "❌ ERROR: Direct 'poc → production' merge is forbidden."
            exit 1
          fi

          echo "✅ Branch flow is valid."
